# Generated by Django 4.2 on 2023-04-19 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0005_alter_chapter_date_create'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('user_view_book', 'Can view book'),)},
        ),
    ]
