# Generated by Django 4.1.7 on 2023-07-25 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0006_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={},
        ),
    ]
